### ISSUE TITLE
Interrupted Spell Casting

### ISSUE THREAD

**Issue by loliver1823** [m-vlad/Yggdrasil-VR#97]
When shooting a spell for an extended period, it sometimes gets interrupted by what I think is me buffing myself. It seems to be random, it's sometimes during casting or when I start casting. Not sure whats happening but I see some sort of magic effect swirl around my character when it happens.

**Desktop (please complete the following information):**
 - Yggdrasil VR version: 2.1
 - Storage type Yggdrasil VR is installed on: SSD
 - OS version: Windows 10
 - RAM: 32gb
 - CPU: AMD Ryzen 9 5900X
 - GPU: Nvidia 1080ti
 - Antivirus Windows Defender

**Comment by CritLoren** [comment]
Hello, I looked more into it, this is caused by [Just Cast It - Lite](https://www.nexusmods.com/skyrimspecialedition/mods/62385/). I wasn't sure if I'd removed the mod but it seems it's still included. You can read more about it in the mod description, but it basically adds a chance for spells to fail casting both for you and NPCs if your magic skill is too low compared to the level tier of that spell (novice, apprentice, etc).
